# Render Blueprint Spec: https://render.com/docs/blueprint-spec
# Minimal test for postgresql service

services:
  # --------------------
  # Managed Databases
  # --------------------
  - type: pserv
    name: postgresql-db-test # Using a slightly different name for the test
    plan: free
    postgres:
      version: 15
    region: oregon # Or your preferred region
