"""Implement canonical and mentioned taxonomy

Revision ID: 16067fd1223d
Revises: 12aa9e642bb9
Create Date: 2025-06-25 20:17:07.132075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16067fd1223d'
down_revision = '12aa9e642bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_taxonomy', schema=None) as batch_op:
        batch_op.drop_column('specific_term')

    with op.batch_alter_table('llm_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verbatim_term', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('relevance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('llm_analysis_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('taxonomy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('category')
        batch_op.drop_column('keyword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('taxonomy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('llm_analysis_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_date')
        batch_op.drop_column('relevance_score')
        batch_op.drop_column('verbatim_term')

    with op.batch_alter_table('keyword_taxonomy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specific_term', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
