"""Add processing_time field to Document model

Revision ID: 2f6ca941dbdf
Revises: 32350401d3bb
Create Date: 2025-02-26 00:06:33.681315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6ca941dbdf'
down_revision = '32350401d3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_time', sa.Float(), nullable=True))

    with op.batch_alter_table('llm_analysis', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_analysis', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('processing_time')

    # ### end Alembic commands ###
