"""Add dropbox sync table

Revision ID: 32350401d3bb
Revises: 66c911d0d090
Create Date: 2025-02-05 19:02:24.753277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32350401d3bb'
down_revision = '66c911d0d090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropbox_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('dropbox_file_id', sa.String(length=255), nullable=True),
    sa.Column('dropbox_path', sa.String(length=512), nullable=True),
    sa.Column('sync_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dropbox_file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dropbox_syncs')
    # ### end Alembic commands ###
