"""Remove DocumentKeyword model

Revision ID: 38338ee4e36e
Revises: cc1a8e4fe915
Create Date: 2025-05-07 17:13:29.630542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38338ee4e36e'
down_revision = 'cc1a8e4fe915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taxonomy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extraction_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_keywords_document_id_fkey'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['keyword_taxonomy.id'], name='document_keywords_taxonomy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_keywords_pkey')
    )
    # ### end Alembic commands ###
