"""add search_vector to documents

Revision ID: 8b298fa7a6ba
Revises: 16067fd1223d
Create Date: 2025-06-25 20:22:39.127426

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = "8b298fa7a6ba"
down_revision = "16067fd1223d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "search_vector",
            existing_type=postgresql.TSVECTOR(),
            type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
            existing_nullable=True,
            postgresql_using="NULL::vector",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "search_vector",
            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
            type_=postgresql.TSVECTOR(),
            existing_nullable=True,
            postgresql_using="NULL::tsvector",
        )

    # ### end Alembic commands ###
