"""Add taxonomy_id to llm_keywords

Revision ID: cc1a8e4fe915
Revises: d95570e991c6
Create Date: 2025-05-07 16:13:25.912062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1a8e4fe915'
down_revision = 'd95570e991c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'keyword_taxonomy', ['taxonomy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_keywords', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('taxonomy_id')

    # ### end Alembic commands ###
