"""Initial migration

Revision ID: 326a84e6b998
Revises: 
Create Date: 2025-04-03 19:47:08.190919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326a84e6b998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('primary_category', sa.Text(), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('specific_term', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['keyword_taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('synonym', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['keyword_taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('extraction_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['keyword_taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('feedback_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_feedback')
    op.drop_table('document_keywords')
    op.drop_table('keyword_synonyms')
    op.drop_table('keyword_taxonomy')
    # ### end Alembic commands ###
